name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write
  pages: write
  id-token: write

env:
  PYTHON_VERSION: "3.10"
  NODE_LTS_VERSION: "22.x"

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check-markdown:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: '.'
          config-file: '.github/markdown-link-check-config.json'
  check-tokens:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Tokens
        run: |
          make check-tokens

  build-site:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build Site
        run: |
          make site-build
          
      - name: Upload Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
          
  release:
    needs: [check-markdown, check-tokens, build-site]
    runs-on: ubuntu-24.04
    outputs:
      released: ${{ steps.release-please.outputs.release_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          manifest-file: .github/release-please-manifest.json
          config-file: .github/release-please-config.json

  deploy-site:
    needs: [release, build-site]
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  attach-assets:
    needs: release
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Attach assets to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ./docs/*; do
            gh release upload "${{ needs.release.outputs.tag }}" --clobber "${file}"
          done
